"""Alterar color_depth para texto

Revision ID: 51770a1dfcc1
Revises: 
Create Date: 2025-12-09 23:58:00.458297

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51770a1dfcc1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image_metadata', schema=None) as batch_op:
        batch_op.alter_column('color_depth',
               existing_type=sa.INTEGER(),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image_metadata', schema=None) as batch_op:
        batch_op.alter_column('color_depth',
               existing_type=sa.Text(),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
